### PR TITLE
test: Fix state sync flakes

### LINKED ISSUE #1357: Fix state sync flaky tests
There are two flaky state sync tests:
```
TestResumeSyncAccountsTrieInterrupted
TestResyncNewRootAfterDeletes
```

### PR DESCRIPTION
**Pull request by alarso16**
## Why this should be merged

Since the state syncer can have multiple workers, there may be multiple in flight requests when it should start returning errors. Therefore, the number may be atomically increased more than twice.

For the other test, I haven't been able to replicate it locally. In order to see it flake (if it still does), I think we should remove it from the list of flakes

Closes #1357

## How this works

Provides lower bound.

## How this was tested

Unable to reproduce, likely needs small machine.

## Need to be documented?

No.

## Need to update RELEASES.md?

No.

### CODE REVIEW

**Review by powerslider — APPROVED** [review]

File: sync/statesync/sync_test.go [hunk 1]
```diff
@@ -260,7 +260,7 @@ func TestResumeSyncAccountsTrieInterrupted(t *testing.T) {
 		GetLeafsIntercept: intercept.getLeafsIntercept,
 	})
 
-	require.Equal(t, uint32(2), intercept.numRequests)
+	require.LessOrEqual(t, uint32(2), intercept.numRequests.Load())
```
Comment (StephenButtolph) [inline sync/statesync/sync_test.go]: At a glance, I thought "less than or equal" "2" "numRequests" and incorrectly thought that the thing under test needed to be leq 2.
```suggestion
	require.GreaterOrEqual(t, intercept.numRequests.Load(), uint32(2))
```
Since we actually want the thing under test to be at _least_ 2, should we be using `GreaterOrEqual`?
